name: Maven CI with Dependabot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -V test -Ddoclint=all --file pom.xml --no-transfer-progress

  dependabot:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github_token: "${{ secrets.github_token }}"
      - name: Apply label
        run: gh pr edit "$PR_URL" --add-label "automerge"
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.github_token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.github_token }}
          PR_URL: ${{ github.event.pull_request.html_url }}